# Railway Config File for Django Project
# nixpacks.toml

[phases.setup]
nixPkgs = ['python39', 'postgresql', 'git']  # Define required Nix packages

[phases.build]
cmds = [
    'pip install -r requirements.txt',  # Install Python dependencies
    'python manage.py collectstatic --noinput',  # Collect static files
]

[start]
cmd = 'gunicorn myproject.wsgi:application --bind 0.0.0.0:8000'  # Start Gunicorn server


# Build Settings
[build]
  steps = [
    { name = "Install Dependencies", command = "pip install -r requirements.txt" }
  ]

# Run Settings
[run]
  web = "gunicorn rena.wsgi:application"

# Environment Variables
[env]
  DJANGO_SECRET_KEY = "django-insecure-g%w66t842#txf-n18umex_!0bc*2typn^qi$bmda(1ddtd2re4"
  DATABASE_URL = "sqlite:///db.sqlite3"

# Dependencies
[dependencies]
  python = { version = "3.8" }

# Deployment Settings
[deploy.production]
  branch = "main"
  commands = [
    "python manage.py migrate",
    "python manage.py collectstatic --no-input"
  ]
